services:

  tririga-db2:
    image: icr.io/db2_community/db2:11.5.9.0
    container_name: tririga-db2
    privileged: true
    restart: unless-stopped

    environment:
      LICENSE: accept
      DB2INSTANCE: db2inst1
      DBNAME: TRIRIGA
      DB2INST1_PASSWORD: S0ftw@re

    ports:
      - "50000:50000"

    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/127.0.0.1/50000'"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 90s

    volumes:
      - db2-data:/database

  tririga-app:
    build: .
    container_name: tririga-app
    restart: unless-stopped

    depends_on:
      tririga-db2:
        condition: service_healthy

    ports:
      - "8001:8001"
      - "8443:8443"

volumes:
  db2-data:
